version: '3.9'

services:
  selenium:
  image: selenium/standalone-chrome
  platform: linux/amd64
  container_name: selenium
  ports:
    - 4444:4444
    - 7900:7900
  shm_size: '2gb'
  healthcheck:
    test: ["CMD", "curl", "-f", 'http://localhost:4444']
    interval: 10s
  networks:
    - td

networks:
  td:
    name: td_network